// Generated by CoffeeScript 1.6.3

/*
  Node class.
  keeps track of
    - previous node
    - next node
    - data (payload)
*/

(function() {
  var Node;

  Node = (function() {
    function Node(prev, next, data) {
      this.prev = prev;
      this.next = next;
      this.data = data;
      null;
    }

    Node.prototype.name = 'Node';

    Node.prototype.isTailNode = function() {
      return this.next === null;
    };

    Node.prototype.isHeadNode = function() {
      return this.prev === null;
    };

    Node.prototype.remove = function() {
      var prop, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        prop = this[_i];
        _results.push(delete this.prop);
      }
      return _results;
    };

    return Node;

  })();

  module.exports = Node;

}).call(this);
