// Generated by CoffeeScript 1.6.3

/*
  Node class. Double-linked node.
  keeps track of
    - previous node
    - next node
    - data (payload)
*/

(function() {
  var Node;

  Node = (function() {
    function Node(prev, next, data) {
      this.prev = prev;
      this.next = next;
      this.data = data;
      null;
    }

    Node.prototype.isTailNode = function() {
      return this.next === null;
    };

    Node.prototype.isHeadNode = function() {
      return this.prev === null;
    };

    Node.prototype.belongsToNoList = function() {
      return this.prev === null && this.next === null;
    };

    Node.prototype.remove = function() {
      this.next = null;
      this.prev = null;
      return this.data = null;
    };

    return Node;

  })();

  module.exports = Node;

}).call(this);
